/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IFeature } from "./types";
export namespace Components {
    interface DiscussionsWidget {
        "mapId"?: string;
    }
    interface ElementProvider {
        "context"?: any;
        "element"?: HTMLElement;
        "scope": string;
    }
    interface MapWidget {
        "addFeature": (feature: IFeature) => Promise<void>;
    }
}
declare global {
    interface HTMLDiscussionsWidgetElement extends Components.DiscussionsWidget, HTMLStencilElement {
    }
    var HTMLDiscussionsWidgetElement: {
        prototype: HTMLDiscussionsWidgetElement;
        new (): HTMLDiscussionsWidgetElement;
    };
    interface HTMLElementProviderElement extends Components.ElementProvider, HTMLStencilElement {
    }
    var HTMLElementProviderElement: {
        prototype: HTMLElementProviderElement;
        new (): HTMLElementProviderElement;
    };
    interface HTMLMapWidgetElement extends Components.MapWidget, HTMLStencilElement {
    }
    var HTMLMapWidgetElement: {
        prototype: HTMLMapWidgetElement;
        new (): HTMLMapWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "discussions-widget": HTMLDiscussionsWidgetElement;
        "element-provider": HTMLElementProviderElement;
        "map-widget": HTMLMapWidgetElement;
    }
}
declare namespace LocalJSX {
    interface DiscussionsWidget {
        "mapId"?: string;
    }
    interface ElementProvider {
        "context"?: any;
        "element"?: HTMLElement;
        "scope"?: string;
    }
    interface MapWidget {
    }
    interface IntrinsicElements {
        "discussions-widget": DiscussionsWidget;
        "element-provider": ElementProvider;
        "map-widget": MapWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "discussions-widget": LocalJSX.DiscussionsWidget & JSXBase.HTMLAttributes<HTMLDiscussionsWidgetElement>;
            "element-provider": LocalJSX.ElementProvider & JSXBase.HTMLAttributes<HTMLElementProviderElement>;
            "map-widget": LocalJSX.MapWidget & JSXBase.HTMLAttributes<HTMLMapWidgetElement>;
        }
    }
}
